# -*- coding: utf-8 -*-
"""Mi bot de discord AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzYpfD2IgE02DW5-J9Y3wawasXsEpwZ4
"""

!pip install discord

!unzip ./converted_keras.zip

import PIL
PIL.__version__
!pip install -q tf-keras==2.19.0 h5py==3.11.0
import tf_keras as keras  # Importando tf-keras – una versión de Keras compatible con modelos .h5
from tf_keras.models import load_model  # Importando la función load_model de tf_keras, que nos permite abrir el modelo
from PIL import Image, ImageOps  # Importar las clases Image e ImageOps de la biblioteca PIL
import numpy as np

def get_class(model_path, labels_path, image_path):
  np.set_printoptions(suppress=True)
  model = load_model(model_path, compile=False)
  class_names = open(labels_path, "r").readlines()
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
  image = Image.open(image_path).convert("RGB")
  size = (224, 224)
  image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
  image_array = np.asarray(image)
  normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1
  data[0] = normalized_image_array
  prediction = model.predict(data)
  print(prediction)
  index = np.argmax(prediction)
  class_name = class_names[index]
  confidence_score = prediction[0][index]
  text1 = f"Class: {class_name[2:]} Confidence Score: {confidence_score}"
  return text1

import discord
from discord.ext import commands
import nest_asyncio

nest_asyncio.apply()

intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix='$', intents=intents)

@bot.event
async def on_ready():
    print(f'We have logged in as {bot.user}')

@bot.command()
async def heh(ctx, count_heh = 5):
    await ctx.send("he" * count_heh)

@bot.command()
async def check(ctx):
  if ctx.message.attachments:
    for archivo in ctx.message.attachments:
      file_name = archivo.filename
      file_url = archivo.url
      await archivo.save(f"./{file_name}")
      await ctx.send("Archivo guardado exitosamente")
      await ctx.send(get_class("./keras_model.h5", "labels.txt", f"./{file_name}"))

  else:
    await ctx.send("No se encontraron archivos en el mensaje")


bot.run("MTQyMjM1ODc2OTkyODc2OTczNg.GEVoBr.m_VtZlgQP2yjt6tJ4chgCfefFOyITgmc7sm4MY")